<?php

/*@Green Api Framework [An Open Source API Framework Based On PHP]
 *@Developer Agency: Green Box
 *@Publisher Agency: Open Source Solver
 *@Author: Green Box & Open Source Solver
 *@Copyright: Green Box & Open Source Solver
 *@Copyright Under: http://creativecommons.org/licenses/by-nc-sa/4.0/
 *@Contact: gr33nbox.work@gmail.com, www.gr33nbox.work
 *@Address: Dhaka, Bangladesh
 */

/*@FileName: phpiniconfig.inc
 *@FileCreator: Green Box Admin
 *@Comments: PHP ini Config
 */
//START//
// Set default timezone
date_default_timezone_set('Asia/Dhaka');
// Set display_errors
ini_set('display_errors', 'Off');
// Set max_execution_time
ini_set('max_execution_time', '30');
